name: "Build"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the project
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Installing the dependencies
        run: npm install

      - name: Building the project
        run: npm run all
