name: "Build"
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the project
        uses: actions/checkout@v3

      - name: Installing the dependencies
        run: npm install

      - name: Building the project
        run: npm run all
