name: "Release"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checking out the project
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Installing the dependencies
        run: npm install

      - name: Building the project
        run: npm run all

      - id: releaser
        name: New Version Decider
        uses: thiagodonferreira/new-version-decider@v0.0.7
        with:
          loader: nodejs
          configurationFile: ./package.json

      - name: Create Release on Github
        uses: softprops/action-gh-release@v1
        if: ${{steps.releaser.outputs.shouldGenerateANewVersion == 'true' }}
        with:
          name: ${{ steps.releaser.outputs.currentVersion }}
          tag_name: v${{steps.releaser.outputs.currentVersion}}
          # files: "*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publishing it to registry
        uses: JS-DevTools/npm-publish@v1.0.0
        if: ${{steps.releaser.outputs.shouldGenerateANewVersion == 'true' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
